language: node_js
node_js: node
 deploy:
  provider: heroku
  api_key:
    secure: cb7f4792-9609-4fe4-9e13-096a6cd48712
  app: mysterious-shore-13236
  on:
    repo: JLinnell/macgyver
cache:
  directories:
    - node_modules
env:
  - CI=true